name = "OnlineTechnicalIndicators"
uuid = "dc2d07fb-478f-4566-8417-81bb3e5a7af1"
authors = ["FemtoTrader"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OnlineStatsBase = "925886fa-5bf2-5e8e-b522-a9147a512338"
OnlineStatsChains = "c3092dcd-a09e-45f3-b86d-18109bff285f"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
OnlineStatsBase = "1"
OnlineStatsChains = "0.3"
Tables = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
